### ISSUE TITLE
doesn't show up in mobile browsers?

### ISSUE THREAD

**Issue by CLhilaoneg** [KnowsCount/qiokian#7]
i tried everyone of the browsers that i can reach on my apple phone... but none of them work.

**Comment by KnowsCount** [comment]
you can change that by modifying this [line](https://github.com/KnowsCount/qiokian/blob/8e17c5f9702a9b4e6a93a781abccaed5772f7ca0/src/qiokian.vue#L29).

this happens because the assets are only loaded when the screen width is greater than equal to 768.

```vue.js
if (screen.width >= 768) {
```
